# Generated by Django 5.2.6 on 2025-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
